Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "vm" do |vm|
    # first parameter is path on the Host and second is path on guest
    config.vm.box = "bento/ubuntu-18.04"
    config.vm.synced_folder "/Users/thawngzapumlian/vagrant-synced", "/vagrant-synced"
    config.vm.provider :virtualbox do |vb|
      vb.name = "vm1-bento-ubuntu-1804"
    end
  end
  
  config.vm.define "vm2" do |vm2|
    config.vm.box = "bento/ubuntu-18.04"
    # config.vm2.synced_folder "/Users/thawngzapumlian/vagrant-synced", "/vagrant-synced"
    config.vm.provider :virtualbox do |vb|
      vb.name = "vm2-bento-ubuntu-1804"
    end
  end
end
