---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: salesforce/server2016
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[onboard-luns::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes: <%= IO.read('test/lunids.json') %>
