pipeline {
      agent {
          label 'linux'
      }
      stages {
          stage('Lint') {
              steps {
                  wrap([$class: 'AnsiColorBuildWrapper']) {
                      sh 'foodcritic .'
                      sh 'cookstyle --color'
                  }
              }
          }
          stage('Kitchen') {
              steps {
                  wrap([$class: 'AnsiColorBuildWrapper']) {
                      sh 'for i in `kitchen list -b`; do kitchen create $i && kitchen verify $i && kitchen destroy $i; done'
                  }
              }
          }
          stage('Knife Upload') {
              when { branch "master" }
              steps {
                  echo 'Uploading cookbook to Chef master...'
                  wrap([$class: 'AnsiColorBuildWrapper']) {
                      sh 'berks install && berks upload --ssl-verify=false'
                  }
              }
          }
      }
  }
